name: qrx_pro
description: "QRX Pro — A professional QR generator and scanner built with Flutter."
publish_to: 'none' # Prevents accidental publishing to pub.dev

# Versioning
# Format: major.minor.patch+build
version: 1.0.0+1

# Environment
environment:
  sdk: ^3.9.2

# -------------------------
# 📦 Dependencies
# -------------------------
dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  lucide_icons: ^0.257.0
  flutter_native_splash: ^2.4.6

  # Navigation & DI
  go_router: ^16.2.5
  get_it: ^8.2.0
  injectable: ^2.4.2

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # State Management
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.1

  # Permissions & Device Info
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0

  # QR & File Handling
  mobile_scanner: ^7.1.2
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  csv: ^6.0.0
  archive: ^4.0.7
  flutter_file_dialog: ^3.0.2
  gal: ^2.2.0
  uuid: ^4.4.0
  pdf: ^3.11.0

  # Sharing, Links & Time
  share_plus: ^12.0.0
  url_launcher: ^6.3.0
  timeago: ^3.7.1
  

# -------------------------
# 🧪 Dev Dependencies
# -------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  hive_generator: ^2.0.1
  freezed: ^2.5.2

  # Code Quality
  flutter_lints: ^6.0.0

# -------------------------
# 🎨 Flutter Configuration
# -------------------------
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/

